SomEKart/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SomEKart.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SomEKart/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using log4net;
using log4net.Config;
using Microsoft.AspNetCore.Mvc;
using SomEKart.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SomEKart.Controllers
{
    public class InventoryController : Controller
    {
        private static readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private readonly IInventoryRepository _invetoryRepository;

        public InventoryController(IInventoryRepository invetoryRepository)
        {
            _invetoryRepository = invetoryRepository;
        }
        
        //public ViewResult List()
        //{
        //    _log.Info("Loading inventory...");
        //    ViewBag.Title = "Som's E-Kart";
        //    return View(_invetoryRepository.GetAllItems());
        //}

        public ViewResult List(string category)
        {
            _log.Info("Loading category wise inventory...");
            ViewBag.Title = "Som's E-Kart";

            IEnumerable<Item> items = null;
            Category cat;
            var parsed = Enum.TryParse<Category>(category, out cat);

            if (string.IsNullOrEmpty(category) || !parsed)
            {
                items = _invetoryRepository.GetAllItems();
            }
            else
            {
                items = _invetoryRepository.GetAllItems().Where(a => a.Category == cat);
            }

            return View(items);
        }

        public IActionResult Details(int id)
        {
            int qty;
            var item = _invetoryRepository.GetItem(id, out qty);
            if (qty == 0)
                return NotFound();
            return View(item);
        }
    }
}

SomEKart/Views/Shared/_ItemCard.cshtml
@model Item

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageUrl" alt="ASP.NET" class="img-responsive" />
        <div class="caption">
            <h3 class="pull-right"> 
                @{ 
                    CultureInfo ci = CultureInfo.GetCultureInfo("en-IN");
                    @Model.Price.ToString("c", ci)
                 }
            </h3>
            <h3>
                <a asp-controller="Inventory" asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a>
            </h3>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-itemId="@Model.Id">Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

SomEKart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Somnath's E-Kart</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/content/site_style.css")" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li>
                        <a asp-controller="Contact" asp-action="Index">Contact</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <p class="lead">
                    <img class="img-responsive" alt="Som's E-Kart" src="~/images/somnath.jpg" />
                </p>
                <p style="font-size: large">Somnath's E-Kart</p>
            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Som's E-Kart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>